### ISSUE TITLE
putsreq app not starting

### ISSUE THREAD

**Issue by ddavtian** [phstc/putsreq#43]
Thank you for a great application. Given the latest issues with the hosted version going up/down frequently throughout the day I decided to run my own. I ran into the following issue, hoping that you can help?

`docker-compose up -d`

```
docker logs -f e82bddc68903
bin/rails: Devise.secret_key was not set. Please add the following to your Devise initializer: (RuntimeError)

  config.secret_key = '29f0704f974f5321371f4cc3bce47f68534fa70b5d48db5f1aaf74185c3374d7459274418b8f0594a38d614fc59fe5f9dee72ffe383e906dd06971985a5bf649'

Please ensure you restarted your application after installing Devise or setting the key.
=> Booting Puma
=> Rails 5.1.7 application starting in development
=> Run `rails server -h` for more startup options
Exiting
```

:pushpin: #47

**Comment by phstc** [comment]
> Thank you for a great application

❤️ 

@ddavtian could you pull master and try again? 

```sh
docker-compose build
docker-compose up
```

I updated it with the required env variables.

**Comment by ddavtian** [comment]
thank you @phstc things are looking better, the containers are up, although ran into the following exception when I clicked on "Create a PutsReq"

```
[Webpacker] Compiling…
app_1    | [Webpacker] Compilation failed:
app_1    | bundler: failed to load command: webpack (/usr/local/bundle/bin/webpack)
app_1    |
app_1    | Errno::ENOENT: No such file or directory - /app/node_modules/.bin/webpack
app_1    |   /usr/local/bundle/gems/webpacker-3.2.0/lib/webpacker/webpack_runner.rb:11:in `exec'
app_1    |   /usr/local/bundle/gems/webpacker-3.2.0/lib/webpacker/webpack_runner.rb:11:in `block in run'
app_1    |   /usr/local/bundle/gems/webpacker-3.2.0/lib/webpacker/webpack_runner.rb:10:in `chdir'
app_1    |   /usr/local/bundle/gems/webpacker-3.2.0/lib/webpacker/webpack_runner.rb:10:in `run'
app_1    |   /usr/local/bundle/gems/webpacker-3.2.0/lib/webpacker/runner.rb:6:in `run'
app_1    |   /usr/local/bundle/gems/webpacker-3.2.0/exe/webpack:8:in `<top (required)>'
app_1    |   /usr/local/bundle/bin/webpack:23:in `load'
app_1    |   /usr/local/bundle/bin/webpack:23:in `<top (required)>'
app_1    |
app_1    |   Rendered buckets/show.html.erb within layouts/application (645.9ms)
app_1    | Completed 500 Internal Server Error in 746ms
app_1    |
app_1    |
app_1    |
app_1    | ActionView::Template::Error (Webpacker can't find application.js in /app/public/packs/manifest.json. Possible causes:
app_1    | 1. You want to set webpacker.yml value of compile to true for your environment
app_1    |    unless you are using the `webpack -w` or the webpack-dev-server.
app_1    | 2. webpack has not yet re-run to reflect updates.
app_1    | 3. You have misconfigured Webpacker's config/webpacker.yml file.
app_1    | 4. Your webpack configuration is not creating a manifest.
app_1    | Your manifest contains:
app_1    | {
app_1    | }
app_1    | ):
```

**Comment by phstc** [comment]
@ddavtian oh I had a `node_modules` already, that's why it worked for me. I hopefully fix it in #47, could you git pull, build and up again? 🤞

**Comment by ddavtian** [comment]
thank you very much @phstc 👍

**Comment by phstc** [comment]
@ddavtian did it work? 🙏

**Comment by ddavtian** [comment]
@phstc works like a champ now :-)

**Comment by phstc** [comment]
![](https://media.giphy.com/media/J6VR03Q4GRO12/giphy.gif)
